Repository benthayer/git-gud, pull requests merged in 2020-08, with the labels that each got.

#283 Added prompt counter to git gud explain
  gitgud/skills/level_builder.py
Labels: needs-review

#252 Added automatic asciinema generation
  .github/workflows/generate-preview.yml
  preview.gif
  previewgif.sh
  previewgif_cmd.txt
Labels: waiting

#285 Ignore branch capitalization for branches created by user
  gitgud/skills/level_builder.py
  gitgud/skills/parsing.py
  gitgud/skills/test_parsing.py
Labels: needs-review

#241 Track level progress
  gitgud/__main__.py
  gitgud/operations.py
  gitgud/skills/level_builder.py
  gitgud/skills/user_messages.py
  gitgud/test_operator.py
Labels: needs-changes

#273 An Easy Level
  gitgud/skills/__init__.py
  gitgud/skills/rewriting/__init__.py
  gitgud/skills/rewriting/_easy/details.yaml
  gitgud/skills/rewriting/_easy/explanation.txt
  gitgud/skills/rewriting/_easy/goal.txt
  gitgud/skills/rewriting/_easy/setup.spec
  gitgud/skills/rewriting/_easy/solution.txt
  gitgud/skills/rewriting/_easy/test.spec
  gitgud/skills/rewriting/test_levels.py
  setup.py
Labels: needs-review
